FROM node:20.19-alpine3.20 AS base
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
ENV SKIP_ENV_VALIDATION="true"
ENV DOCKER_OUTPUT=1
ENV NEXT_TELEMETRY_DISABLED=1
ENV NEXT_PUBLIC_IS_CLOUD="false"

RUN corepack enable
RUN corepack prepare pnpm@latest --activate

FROM base AS builder
RUN apk add --no-cache libc6-compat
RUN apk update
WORKDIR /app

COPY package.json pnpm-lock.yaml pnpm-workspace.yaml turbo.json ./
COPY ./apps/web ./apps/web
COPY ./packages ./packages
RUN pnpm add turbo@^2.5.2 -g

# Prune monorepo for web app dependencies
RUN pnpm turbo prune web --docker

FROM base AS installer
RUN apk add --no-cache libc6-compat
RUN apk update
WORKDIR /app

COPY .gitignore .gitignore
COPY --from=builder /app/out/json/ .
COPY --from=builder /app/out/pnpm-lock.yaml ./pnpm-lock.yaml
RUN --mount=type=cache,id=pnpm,target=/pnpm/store pnpm install --frozen-lockfile

ARG APP_VERSION=unknown
ARG GIT_SHA=unknown

ENV NEXT_PUBLIC_APP_VERSION=$APP_VERSION
ENV NEXT_PUBLIC_GIT_SHA=$GIT_SHA

COPY --from=builder /app/out/full/ .

RUN pnpm turbo run build --filter=web...

FROM base AS runner
WORKDIR /app

COPY --from=installer /app .
COPY ./docker/start.sh ./start.sh
RUN chmod +x ./start.sh

ENV SKIP_ENV_VALIDATION="false"

EXPOSE 3000

CMD ["sh", "start.sh"]
