export const PLAN_PERKS = {
  FREE: [
    "12,500 emails / month (hard cap)",
    "5,000 emails / day (hard cap)",
    "Transactional emails included",
    "Marketing emails not available",
    "Up to 2 domains + $1/extra",
    "Up to 5 team members",
    "Community support",
  ],
  HOBBY: [
    "25,000 emails / month included",
    "12,500 emails / day",
    "Marketing CA$0.05/ea (overage)",
    "Up to 4 domains + $1/extra",
    "Up to 10 team members",
    "Community support",
  ],
  LITE: [
    "50,000 emails / month included",
    "25,000 emails / day",
    "Marketing CA$0.02/ea (overage)",
    "Up to 6 domains + $1/extra",
    "Up to 15 team members",
    "Priority support",
  ],
  BASIC: [
    "150,000 emails / month included",
    "Unlimited daily sending",
    "Transactional CA$0.01/ea (overage)",
    "Marketing CA$0.01/ea (overage)",
    "Up to 100 domains + $1/extra",
    "Priority support",
    "Advanced analytics",
  ],
  LIFETIME: [
    "One-time CA$60 payment",
    "Unlimited emails — no overage charges",
    "Marketing & transactional included",
    "Up to 500 domains + $1/extra",
    "Priority support",
    "Advanced analytics",
  ],
};
